### DISCUSSION TITLE
容器平台支持 yaml 导入设计

### DISCUSSION THREAD

**Discussion by poneding** [wutong-paas/wutong#14] [Ideas]
在采用容器平台之前，面向已经拥有 Kubernetess 能力的用户，我们一直有这样一个需求：容器平台支持 K8s yaml 原生资源的导入。

我们将导入的资源区分为工作负载资源和非工作负载资源：

1、**工作负载资源**：`Deployment`、`StatefulSet`

2、**非工作负载资源**：`Service`、`Ingress`、`ServiceAccoount`、`Secret`等

**说明**：由于容器平台的组件类型，`DaemonSet`、`CronJob`等资源也一并视为非工作负载资源

### 导入工作负载

支持的资源类型：

-   Deployment：无状态应用组件
-   StatefulSet：有状态应用组件

⚠️ 注意：根据负载的实例数量（Replicas）字段确定是组件是多实例还是单实例。

对于简单的 yaml 工作负载内容，我们可以直接使用如下图的解析方式，来创建梧桐应用组件模型。

![image-20230418090952801](https://pding.oss-cn-hangzhou.aliyuncs.com/images/202304180909913.png)

很多时候，由于梧桐应用组件模型与Kubernetes运行单元Pod之间存在的配置差，导致我们无法将原生工作负载强转为梧桐应用组件。

为此，我们首先需要让梧桐应用组件模型支持更多的原生Pod配置，例如：

-   多容器（Containers）
-   环境变量高级引用（EnvRefFrom）
-   节点容忍（Tolerations）
-   节点/Pod亲和性（Affinity）
-   ...

![image-20230418092602022](https://pding.oss-cn-hangzhou.aliyuncs.com/images/202304180926056.png)

### 导入非工作负载

对于非工作负载，直接在集群中创建，用户可以看到创建状态，并允许对其进行更新、删除。

## 流程设计

流程图如下：

![image-20230418094854842](https://pding.oss-cn-hangzhou.aliyuncs.com/images/202304180948870.png)

对于工作负载，将 yaml 内容解析成**梧桐应用组件标准模型** + **Workload 差异配置**（json 格式存储，便于后续追加新字段）

### 组件类型

**Deployment**

spec.replicas > 1 (默认为1) ：无状态多实例，否则无状态单实例

**StatefulSet**

spec.replicas > 1 (默认为1) ：有状态多实例，否则有状态单实例

### 镜像名称

`<deployment/statefulSet>.spec.template.spec.containers[0].image`

### 启动命令

`<deployment/statefulSet>.spec.template.spec.containers[0].command` + `<deployment/statefulSet>.spec.template.spec.containers[0].args`

```yaml
command:
- redis-server
args:
- --appendonly yes
```

### 环境变量

`<deployment/statefulSet>.spec.template.spec.containers[0].env`

### 伸缩资源

`<deployment/statefulSet>.spec.template.spec.containers[0].resources`

### 端口

`<deployment/statefulSet>.spec.template.spec.containers[0].ports`

### labels

工作负载标签

字段来自 `<deployment/statefulset>.metadata.labels`

```yaml
app-name: wordpress
app-ver: v1.0
```

### annotations

工作负载标签

字段来自 `<deployment/statefulset>.metadata.labels`

```yaml
wutong.io/app-name: wordpress
wutong.io/app-ver: v1.0
```

### initContainers

初始化容器

字段来自 `<deployment/statefulset>.spec.template.spec.initContainers`

```yaml
- name: init-myservice
  image: busybox:1.28
  command: ['sh', '-c', "until nslookup myservice.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2; done"]
- name: init-mydb
  image: busybox:1.28
  command: ['sh', '-c', "until nslookup mydb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done"]
```

### containers

多容器Pod，导入时默认第一个容器为业务容器

字段来自 `<deployment/statefulset>.spec.template.spec.containers`

```yaml
- name: redis
  image: redis
  resources:
    limits:
      memory: "128Mi"
      cpu: "100m"
  ports:
  - name: redis
    containerPort: 6379
    protocol: TCP
```

### envRefs

环境变量高级引用，可以引用ConfigMap，Secret，PodStatus

字段来自 `<deployment/statefulset>.spec.template.spec.containers[0].env`

```yaml
- name: USERNAME
  valueFrom:
    configMapKeyRef:
      name: web-config
      key: username
- name: PASSWORD
  valueFrom:
    secretKeyRef:
      name: web-secret
      key: password
- name: POD_IP
  valueFrom:
    fieldRef:
      fieldPath: status.podIP
```

### resources

资源配置

字段来自 `<deployment/statefulset>.spec.template.spec.containers[0].resources`

```yaml
requests:
  ephemeral-storage: "2Gi"
limits:
  ephemeral-storage: "4Gi"
```

⚠️ 注意：导入时，如果是简单的CPU、内存资源配置， 则加载到梧桐组件模型的资源配置，并且需要转换到正确的数值单位。

### serviceAccountName

Pod 使用服务账号名。（用于分配 Pod 在集群中的操作权限）

字段来自 `<deployment/statefulset>.spec.template.spec.serviceAccountName`

```tex
crd-admin
```

### privileged

Pod 是否开启 privileged 属性

字段来自 `<deployment/statefulset>.spec.template.spec.containers[0].securityContext.privileged`

```tex
true
```

### shareProcessNamespace

Pod 配置进程命名空间共享，当启用进程命名空间共享时，容器中的进程对同一 Pod 中的所有其他容器都是可见的。

字段来自 `<deployment/statefulset>.spec.template.spec.shareProcessNamespace`

```yaml
true
```

### dnsPolicy

字段来自 `<deployment/statefulset>.spec.template.spec.dnsPolicy`

枚举值：

-   Default
-   ClusterFirst
-   ClusterFirstWithHostNet
-   None

```tex
ClusterFirstWithHostNet
```

### dnsConfig

当 dnsPolicy 配置为 None 时才会生效。

字段来自 `<deployment/statefulset>.spec.template.spec.dnsConfig`

```yaml
 nameservers:
 - 192.0.2.1 # 这是一个示例
searches:
- ns1.svc.cluster-domain.example
- my.dns.search.suffix
options:
- name: ndots
  value: "2"
- name: edns0
```

### hostNetwork

Pod 是否使用宿主机网络

字段来自 `<deployment/statefulset>.spec.template.spec.hostNetwork`

```tex
true
```

### nodeName

指定Pod调度到某节点

字段来自 `<deployment/statefulset>.spec.template.spec.nodeName`

```tex
pass-worker-01
```

### nodeSelector

指定Pod调度到某类节点

字段来自 `<deployment/statefulset>.spec.template.spec.nodeSelector`

```yaml
disktype: ssd
```

### lifeCycle

Kubernetes 支持 postStart 和 preStop 事件。 当一个容器启动后，Kubernetes 将立即发送 postStart 事件；在容器被终结之前， Kubernetes 将发送一个 preStop 事件。容器可以为每个事件指定一个处理程序。

字段来自 `<deployment/statefulset>.spec.template.spec.containers[0].lifeCycle`

```yaml
postStart:
  exec:
    command: ["/bin/sh", "-c", "echo Hello from the postStart handler > /usr/share/message"]
preStop:
  exec:
    command: ["/bin/sh","-c","nginx -s quit; while killall -0 nginx; do sleep 1; done"]
```

### livenessProbe

存活探针，如果配置覆盖梧桐组件模型健康检测

字段来自 `<deployment/statefulset>.spec.template.spec.containers[0].livenessProbe`

```yaml
exec:
  command:
  - cat
  - /tmp/healthy
initialDelaySeconds: 5
periodSeconds: 5
```

⚠️ 注意：导入时，如果解析到类型为 httpGet 或者 tcpSocket 则加载到梧桐组件模型的健康检测。

### readinessProbe

就绪探针

字段来自 `<deployment/statefulset>.spec.template.spec.containers[0].readinessProbe`

```yaml
exec:
  command:
  - cat
  - /tmp/healthy
initialDelaySeconds: 5
periodSeconds: 5
```

### tolerations

容忍节点污点

字段来自 `<deployment/statefulset>.spec.template.spec.tolerations`

```yaml
- key: "key"
  operator: "Equal"
  value: "value"
  effect: "NoSchedule"
```

### affinity

字段来自 `<deployment/statefulset>.spec.template.spec.affinity`

调度亲和配置，支持配置节点亲和、Pod 亲和

```yaml
nodeAffinity:
  requiredDuringSchedulingIgnoredDuringExecution:
    nodeSelectorTerms:
    - matchExpressions:
      - key: kubernetes.io/e2e-az-name
        operator: In
        values:
        - e2e-az1
        - e2e-az2
podAffinity:
  requiredDuringSchedulingIgnoredDuringExecution:
  - labelSelector:
      matchExpressions:
      - key: security
        operator: In
        values:
        - S1
    topologyKey: failure-domain.beta.kubernetes.io/zone
podAntiAffinity:
  requiredDuringSchedulingIgnoredDuringExecution:
  - labelSelector:
      matchExpressions:
      - key: security
        operator: In
        values:
        - S2
    topologyKey: kubernetes.io/hostname
```

### statefulVolumeClaimTemplates

有状态工作负载 PV 模版

字段来自 `statefulset.spec.volumeClaimTemplates`

```yaml
- metadata:
    name: www
  spec:
    accessModes: [ "ReadWriteOnce" ]
    resources:
      requests:
        storage: 1Gi
```

### volumes

存储定义

字段来自 `<deployment/statefulset>.spec.template.spec.tolerations`

```yaml
- name: web-config
  configMap:
    name: web-config
```

### volumeMounts

存储挂载

字段来自 `<deployment/statefulset>.spec.template.spec.containers[0].volumeMounts`

```yaml
volumeMounts:
- name: web-config
  mountPath: /etc/config
```

### 工作负载原生特性存储

tenant_env_service_delta_raw_k8s_config

| 字段         | 类型         | 说明                                                       |
| ------------ | ------------ | ---------------------------------------------------------- |
| ID           | int          |                                                            |
| create_time  | datetime     |                                                            |
| config_key   | varchar(50)  |                                                            |
| config_value | longtext     | 存储普通字符串，或者yaml格式内容                           |
| filed_path   | varchar(255) | 工作负载字段路径，例如：deployment.spec.replicas。预留设计 |
| service_id   | varchar(50)  |                                                            |

### 非工作负载资源存储

tenant_env_k8s_resource

| 字段             | 类型        | 说明         |
| ---------------- | ----------- | ------------ |
| ID               | int         |              |
| create_time      | datetime    |              |
| app_id           | varchar(50) |              |
| resource_name    | varchar(50) | 资源名称     |
| resource_content | longtext    | yaml格式内容 |

## 规则

-   导入资源命名空间将自动转换到团队环境命名空间下，您的程序可能需要根据此有所调整，例如服务调用；
-   导入资源工作负载将转换成梧桐应用组件模型，但仍然有可能丢失部分配置，您可以根据需求提交 Issue；
-   当前导入不支持非命名空间资源，例如 ClusterRole，Namespace等。

## 问题

1.   是否允许创建非命名空间资源，例如 ClusterRole，Namespace，这可能涉及最小权限问题；
2.   宿主机端口，挂载宿主机存储问题？
