### DISCUSSION TITLE
梧桐组件存储备份恢复

### DISCUSSION THREAD

**Discussion by poneding** [wutong-paas/wutong#16] [Ideas]
## 目标

为了保证平台有状态组件存储数据安全性和可靠性，提升用户对平台的信任度，平台需要提供组件存储备份&恢复的能力。

-   数据丢失，使用备份数据恢复
-   数据损坏，使用备份数据回滚

## 方案

使用开源社区中成熟的方案 Velero 实现 K8s 存储卷的备份和恢复。

两种备份方式：

-   文件系统备份
-   CSI 快照备份

### 文件系统

文件系统备份，通过 node-agent（Deamonset）读取节点 `/var/lib/kubelet/pods` 存储卷并备份，上传到对象存储系统，例如 Minio。

优点：

-   它能够备份和恢复几乎任何类型的 Kubernetes 卷。因此，如果您的存储平台需要卷快照插件，或者您正在使用 EFS、AzureFile、NFS、emptyDir、本地或任何其他没有本机快照概念的卷类型，FSB 可能适合您。
-   它不依赖于特定的存储平台，因此您可以将备份数据保存到与支持 Kubernetes 卷不同的存储平台，例如持久存储。

注意：

-   它从实时文件系统备份数据，因此备份数据的一致性不如快照方法。

-   它从挂载的主机路径目录访问文件系统，因此 Pod 需要以 root 用户身份运行，甚至在某些环境中需要在特权模式下运行。(node-agent)
-   不支持 hostPath 卷，但支持本地卷类型。

### CSI 快照

通过存储供应器自主实现的 VolumeSnapshot 功能实现存储卷的备份和恢复。

CSI 快照功能实现的前提：

-   需要额外安装 VolumeSnapshot 的 CRD；

-   需要存储类（例如 Longhorn）实现 VolumeSnapshot 的能力；

## 集成方案

对比了 Velero 文件系统和 CSI 快照的备份特性，我们选择了前者，以保证功能的完整性。

在梧桐平台中实现组件的备份，需要使用组件名，组件所在的命名空间，组件 ServiceID 信息进行资源备份，备份了组件的所有 K8s 资源，包括 StatefulSet，Service，Ingress，PV/PVC 等。

### 组件备份

由于需要访问 Pod 所在节点上的卷位置，所以备份时需要确保组件处于运行状态。

创建 Velero Backup 对象，Velero 控制器将执行备份操作，并更新 BackupStatus。

例如：

```yaml
apiVersion: velero.io/v1
kind: Backup
metadata:
  labels:
    velero.io/storage-location: default
    wutong.io/description: "1"
    wutong.io/service_id: 86286650509e1a1e72ffe8679f828f37
  name: app-01-redis-backup-20230901172128
  namespace: velero
spec:
  csiSnapshotTimeout: 10m0s
  defaultVolumesToFsBackup: true
  includedNamespaces:
  labelSelector:
    matchLabels:
      service_id: 86286650509e1a1e72ffe8679f828f37
  storageLocation: default
```

>   使用 --default-volumes-to-fs-backup 参数指定文件系统备份方式。

### 组件恢复

创建 Velero Restore 对象，Velero 控制器将执行恢复操作，并更新 RestoreStatus。

例如：

```yaml
apiVersion: velero.io/v1
kind: Restore
metadata:
  labels:
    velero.io/storage-location: default
    wutong.io/description: "1"
    wutong.io/service_id: 86286650509e1a1e72ffe8679f828f37
  name: app-01-redis-restore-20230901172610
  namespace: velero
spec:
  backupName: app-01-redis-backup-20230901172128
  excludedResources:
  - nodes
  - events
  - events.events.k8s.io
  - backups.velero.io
  - restores.velero.io
  - resticrepositories.velero.io
  - csinodes.storage.k8s.io
  - volumeattachments.storage.k8s.io
  - backuprepositories.velero.io
```

## 界面设计

在 组件 => 存储 界面，新增备份和恢复列表。

![image-20230919110431759](https://pding.oss-cn-hangzhou.aliyuncs.com/images/202309191104841.png)

### 组件备份

地址：`/v2/tenants/{tenant_name}/envs/{tenant_env_name}/services/{service_alias}/backup`

方法：Post

请求：

```json
{
    "service_id": "",
    "desc": ""
}
```

响应：

### 组件恢复

地址：`/v2/tenants/{tenant_name}/envs/{tenant_env_name}/services/{service_alias}/restore`

方法：Post

请求：

```json
{
    "backup_id": "",
    "service_id": ""
}
```

响应：

### 组件备份下载

地址：`/v2/tenants/{tenant_name}/envs/{tenant_env_name}/services/{service_alias}/backup/{backup_id}/download`

方法：Get

请求：

响应：

### 获取组件备份列表

地址：`/v2/tenants/{tenant_name}/envs/{tenant_env_name}/services/{service_alias}/backup/records`

方法：Get

请求：

响应：

```json
[
    {
        "backup_id": "",
        "service_id": "",
        "desc": "",
        "mode": "",
        "created_at": "",
        "completed_at": "",
        "size": "",
        "progress_rate": "",
        "completed_items": 0,
        "total_items": 0,
        "status": "",
    }
]
```

### 获取组件恢复列表

地址：`/v2/tenants/{tenant_name}/envs/{tenant_env_name}/services/{service_alias}/restore/records`

方法：Get

请求：

响应：

```json
[
    {
    	"restore_id": "",
    	"backup_id": "",
    	"service_id": "",
    	"mode": "",
    	"created_at": "",
    	"completed_at": "",
   	 	"size": "",
        "progress_rate": "",
    	"completed_items": 0,
    	"total_items": 0,
    	"status": "",
    }
]
```

### 删除组件备份记录

地址：`/v2/tenants/{tenant_name}/envs/{tenant_env_name}/services/{service_alias}/backup/{backup_id}`

方法：Delete

请求：

响应：

### 删除组件恢复记录

地址：`/v2/tenants/{tenant_name}/envs/{tenant_env_name}/services/{service_alias}/restore/{restore_id}`

方法：Delete

请求：

响应：

### 安装 Minio

-   Docker 安装

    ```shell
    docker run -d --name minio \
        -p 9000:9000 \
        -p 9001:9001 \
        -v /home/dp/Containers/minio/data:/data \
        quay.io/minio/minio:latest server /data --console-address ":9001"
    ```

    >   默认登录账号&密码：minioadmin/minioadmin

-   梧桐组件安装

    略。

安装完成后，需要进入 Minio 的控制台完成以下操作：

1、设置 Region 名称，例如 minio；

2、创建对象存储桶（Bucket），例如 velero；

3、生成 AccessKey 和 SecretKey 供 Velero 访问使用。

### 安装 Velero

-   安装 velero CLI

    ```shell
    # linux
    wget https://github.com/vmware-tanzu/velero/releases/download/v1.11.1/velero-v1.11.1-linux-amd64.tar.gz
    tar -xvf velero-v1.11.1-linux-amd64.tar.gz
    mv velero-v1.11.1-linux-amd64/velero /usr/local/bin
    
    # completion bash
    source /usr/share/bash-completion/bash_completion
    echo 'source <(velero completion bash)' >>~/.bashrc
    velero completion bash >/etc/bash_completion.d/velero
    echo 'alias v=velero' >>~/.bashrc
    echo 'complete -F __start_velero v' >>~/.bashrc
    
    # completion zsh
    source <(velero completion zsh)
    echo 'alias v=velero' >>~/.zshrc
    echo 'complete -F __start_velero v' >>~/.zshrc
    ```

-   集群中安装 Velero （CRD 以及控制器）

    首先将访问 Minio 的 AccessKey 和 SecretKey 配置到凭证文件： 

    ```shell
    cat > credentials-velero <<EOF
    [default]
    aws_access_key_id = xxxxxx
    aws_secret_access_key = xxxxxx
    EOF
    ```

    使用 velero CLI 在目标集群中安装资源：

    ```shell
    velero install \
      --provider aws \
      --plugins velero/velero-plugin-for-aws:main \
      --use-node-agent=true \
      --use-volume-snapshots=false \
      --bucket velero \
      --secret-file ./credentials-velero \
      --backup-location-config \
      --uploader-type=restic \
      region=minio,s3ForcePathStyle="true",s3Url=https://<minio_address>:9000
    ```

-   备份

    ```shell
    velero backup create mysql-backup --selector app=mysql --default-volumes-to-fs-backup
    ```

-   恢复

    ```shell
    velero restore create --from-backup mysql-backup
    ```
